### ISSUE TITLE
bring to front after drag - should be default behaviour

### ISSUE THREAD

**Issue by qyloxe** [quasarframework/app-extension-qwindow#3]
When there are multiple windows, the expected or least surprising behaviour is the the one dragged or resized is brought to front. That's why this:

https://quasarframework.github.io/app-extension-qwindow/examples#Bring-to-Front-After-Drag

should be a default behaviour during dragging/resizing (IMHO).

**Comment by hawkeye64** [comment]
Thanks for the feedback. I'll ask around about the general concensus. However, I don't like components to be so "opinionated" and therefore added a property to do this.

**Comment by qyloxe** [comment]
> Thanks for the feedback. I'll ask around about the general concensus. However, I don't like components to be so "opinionated" and therefore added a property to do this.

haha funny, I thought, that not bringing to front activated windows is "opinionated" :-) I think it is exactly that - activated==front or activated!=front. Why? Because activated state could be fired by click, touch, event, focus, timer etc. Behaviour of this property (bring-to-front-after-drag) is IMHO restricting to only "draggin" when it really means what should happen after "activating" and what methods are possible to "activate" window (drag, click, touch etc.).

**Comment by hawkeye64** [comment]
yes, but yu're messing with `z-index`. Anyway, I tend to agree with yu that it would be "natural" as that's how GUI systems work.

**Comment by hawkeye64** [comment]
Will be fixed in 1.0.0-alpha.3
