### ISSUE TITLE
bring to front after click

### ISSUE THREAD

**Issue by qyloxe** [quasarframework/app-extension-qwindow#4]
When there are multiple windows, when the user clicks on the lower one it is activated but not brought to the front:

![image](https://user-images.githubusercontent.com/467508/62659286-3dbdd100-b96b-11e9-98e5-cbb5853b463e.png)

Bringing window to front after activating is the expected and least surprising behaviour.

**Comment by hawkeye64** [comment]
Thanks for the feedback. If you want this behavior, use the `bring-to-front-after-drag` property.

**Comment by qyloxe** [comment]
> Thanks for the feedback. If you want this behavior, use the `bring-to-front-after-drag` property.

but this issue is about "after click" not "after drag". When you have two windows open in windows, apple, linux, when you click (not drag) on the bottom one, it is brought to front. The mentioned property bring-to-front-after-drag does not help with that. Maybe if you could make that "drag" means "drag" and "click" and "touch" then this behaviour would be consistent with the "windows" in other contexts (ie os windows). Please reopen.

**Comment by hawkeye64** [comment]
ok, I get it now - sorry, a little slow to sink in

**Comment by hawkeye64** [comment]
Fixed in 1.0.0-alpha.4 when released
