### ISSUE TITLE
window events are propagated to main document

### ISSUE THREAD

**Issue by qyloxe** [quasarframework/app-extension-qwindow#5]
There is a quirk with event propagated to the main document. This is a goog example - if you scroll to the end of the q-scroll-area, then the main document is scrolled:

![image](https://user-images.githubusercontent.com/467508/62659537-eec46b80-b96b-11e9-93d5-8aa5a6b378fe.png)

When the mouse is rolled over scroll area inside window, after the end of scroll area, the events are propagated to main page and it is scrolled also. Scrolling over scroll area inside window should not affect the main document. In general, basically any events from qwindows should not be propagated to main document.

**Comment by hawkeye64** [comment]
Agreed. This would be an issue with `QScrollArea`. You can raise an issue with Quasar.

**Comment by qyloxe** [comment]
> Agreed. This would be an issue with `QScrollArea`. You can raise an issue with Quasar.

yep, qscroll should not propagate events, BUT qwindow should be a "barrier" to any events (native and vue) from its child components - not only qscroll but every other component.

**Comment by hawkeye64** [comment]
How would you propose do do that and keep in mind there may also be scrollable content inside a QWindow.

**Comment by qyloxe** [comment]
in qwindow there should be something using this:

https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation

and here are solutions:

https://stackoverflow.com/questions/21724219/stop-propagation-for-all-events

here is how to get a list of all events:

https://stackoverflow.com/questions/5848598/how-can-i-bind-all-events-on-a-dom-element

**Comment by qyloxe** [comment]
now that I think about that, this "event propagation barrier" could be offered in quasar as an extension or mixin. It could be useful for other components/behaviours also.

**Comment by qyloxe** [comment]
and there is a question about distinction for qwindow child events:

- native events should not be propagated

- vue events should be propagated but to the global context (qwindowmanager?)

- native events used for qwindow behaviour should be converted to vue events and propagated to global qwindowmanager. This allows to arrange them or position in relation to each other or minimize all or resize one window when other is resized etc. This is useful when somebody wants to implement very dynamic windows. In the past it was called MDI interface:

https://en.wikipedia.org/wiki/Multiple_document_interface

**Comment by hawkeye64** [comment]
This is something I have decided QWindow should not do when this can be done by the targeted slot data, if the developer so chooses.
